<a href="https://colab.research.google.com/github/Elisantib/SQL_Labo_Murder_Mystery/blob/main/SQL_Labo_Elisa_Murder_Mystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/icarito/UPSK-SQL001-SQLZoo-murder/blob/sql-murder/Sql-Murder-Mystery/SQL_Murder_Mystery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Murder Mystery!
Adapted By: Martin Arroyo.

Edit for: Elisa Santibañez Palma

![Detective making connections between points](https://github.com/freestackinitiative/coop_sql_notebooks/blob/main/assets/sleuth.png?raw=1)

## Escenario

¡Se ha cometido un crimen y los detectives necesitan tu ayuda! Te dieron el informe de la escena del crimen, pero de alguna manera lo perdiste. Recuerdas vagamente que el crimen fue un `murder` _(asesinato)_ que ocurrió en algún momento el 15 de Enero de 2018 y que tuvo lugar en `SQL City`. Depende de ti averiguar quién es el asesino usando solo tus habilidades en SQL y tu ingenio. Te proporcionan una conexión a la base de datos del Departamento de Policía, que tiene todas las pistas que necesitarás para atrapar al asesino.

Usa las habilidades que desarrollaste en SQL 101 y 102, junto con cualquier recurso que desees, para resolver el `SQL Murder Mystery`!"

## Conectandonos a la base de datos del Departamento de Policía

Para comenzar y ejecutar nuestras consultas, presionamos play en la celda de abajo para conectarnos a la base de datos del Departamento de Policía.

Para ejecutar las consultas, creamos una nueva celda de `Code` y escribimos `%%sql` en la parte superior. Luego podemos escribir nuestras consultas debajo.

In [ ]:
%%capture
# @title Press Play { display-mode: "form" }
# Install `teachdb` and `coop_grader`
print("Installing `teachdb` and its dependencies...")
!pip install --quiet --upgrade git+https://github.com/freestackinitiative/teachingdb.git git+https://github.com/martinmarroyo/coop_grader.git
print("Successfully installed `teachdb`")
import pandas as pd
from teachdb.teachdb import connect_teachdb
from coop_grader.sql_murder_mystery.check_suspect import check_suspect
# Set configurations for notebook
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 99)
# Load data
con = connect_teachdb(database="sql_murder_mystery")

%sql con

## Descubriendo tablas en la base de datos

Comenzamos nuestra búsqueda para encontrar al asesino explorando la base de datos del Departamento de Policía. Pero aún no has visto la base de datos y no sabes cuáles son las tablas, así que, ¿cómo sabes qué buscar?

Afortunadamente, la mayoría de los sistemas de gestión de bases de datos relacionales tienen esta información almacenada en un lugar donde puedes consultarla. Muy a menudo, se utiliza un esquema especial conocido como [`information_schema`](https://en.wikipedia.org/wiki/Information_schema) para almacenar información sobre las tablas y columnas en tu base de datos (también conocido como metadata). La base de datos del Departamento de Policía tiene un information schema, con la vista `tables` que te muestra qué tablas están disponibles, y la vista `columns` que te muestra todas las columnas de cada tabla y sus tipos de datos.

### Listando todas las tablas en la base de datos de la Policía

#### Revisa la [descripción de `information_schema.tables`](https://duckdb.org/docs/sql/information_schema.html#tables-and-views)

Primero, veremos todas las tablas disponibles para nosotros consultando la vista `information_schema.tables`. Te daremos la primera consulta para empezar, pero de aquí en adelante tendrás que idear las consultas restantes utilizando tu conocimiento de SQL y tu ingenio.

Aquí está la consulta necesaria para mostrarte las tablas en la base de datos del Departamento de Policía. Cópiala/Pégala en la celda de abajo y ejecútala para ver las tablas disponibles para ti:

>```sql
>SELECT *
>FROM information_schema.tables
>```

In [ ]:
%%sql
SELECT *
FROM information_schema.tables

,table_catalog,table_schema,table_name,table_type,self_referencing_column_name,reference_generation,user_defined_type_catalog,user_defined_type_schema,user_defined_type_name,is_insertable_into,is_typed,commit_action,TABLE_COMMENT
0,memory,main,crime_scene_report,BASE TABLE,None,None,None,None,None,YES,NO,None,None
1,memory,main,drivers_license,BASE TABLE,None,None,None,None,None,YES,NO,None,None
2,memory,main,facebook_event_checkin,BASE TABLE,None,None,None,None,None,YES,NO,None,None
3,memory,main,get_fit_now_check_in,BASE TABLE,None,None,None,None,None,YES,NO,None,None
4,memory,main,get_fit_now_member,BASE TABLE,None,None,None,None,None,YES,NO,None,None
5,memory,main,income,BASE TABLE,None,None,None,None,None,YES,NO,None,None
6,memory,main,interview,BASE TABLE,None,None,None,None,None,YES,NO,None,None
7,memory,main,person,BASE TABLE,None,None,None,None,None,YES,NO,None,None

### Listando todas las tablas y sus columnas en la base de datos de la Policía

**Revisa la [descripción de `information_schema.columns`](https://duckdb.org/docs/sql/information_schema.html#columns)**

¡Genial! Ahora que sabemos qué tablas están disponibles, es hora de averiguar las columnas que tiene cada tabla junto con el tipo de datos de cada columna. Escribimos una consulta que muestre el nombre de la tabla, el nombre de la columna y el tipo de datos para cada tabla en la base de datos del Departamento de Policía utilizando la vista `information_schema.columns`. Nos aseguramos de que la salida esté ordenada por nombre de tabla y luego por nombre de columna (ascendente):

In [ ]:
%%sql

UsageError: %%sql is a cell magic, but the cell body is empty. Did you mean the line magic %sql (single %)?

### Diagrama de Relaciones de Entidad (Opcional)

Después de hacer un poco de trabajo de detective y encontrar las tablas en la base de datos del Departamento de Policía, descubres que hay un ERD (Diagrama de Relaciones de Entidad). Esto puede ser realmente útil en tu búsqueda para encontrar al asesino. Si lo prefieres, desafíate a ti mismo (y tus habilidades en SQL) a continuar solo consultando el `information_schema` según sea necesario. De lo contrario, puedes hacer clic en el desplegable a continuación para revelar el ERD que te ayudará a ver las tablas y las relaciones en la base de datos del Departamento de Policía de un vistazo:

<details>
  <summary>Revisa el ERD del SQL Murder Mystery</summary>
  <img src="https://github.com/freestackinitiative/coop_sql_notebooks/blob/main/assets/murder_mystery_schema.png?raw=1" alt="ERD for SQL Murder Mystery"/>
</details>

___

## Misterio resuelto !!!

Hemos encontrado al asesino con éxito, aplicando nuestras habilidades y las pistas que nos brindó la base de datos del Departamento de Policía para encontrar al asesino.

In [ ]:
check_suspect("Miranda Priestly")

Congrats, you found the brains behind the murder!
Everyone in SQL City hails you as the greatest SQL detective of all time.
Time to break out the champagne!

True

---

## Espacio de Trabajo

Aquí en adelante podrán encontrar todas las consultas que se realizaron en base a la base de datos del Departamento de Policía para encontrar al asesino. Cada una con su debida descripción del caso, hasta que pudimos dar con el sospechoso.

Finalmente el sospechoso fue verificado con éxito.

Usamos la celda de abajo para verificar a nuestro sospechoso, ejecutando su nombre a través de la función `check_suspect`. Si el nombre del sospechoso es correcto, la función nos lo dirá.

No olvidamos usar `%%sql` en la parte superior de las celdas de `Code` para que nuestras consultas SQL funcionen.

##Reuniendo pistas de la escena del crimen

Las imágenes de seguridad muestran que hubo 2 testigos. El primer testigo vive en la última casa de "Northwestern Dr". La segunda testigo, llamada Annabel, vive en algún lugar de "Franklin Ave".

In [ ]:
%%sql

SELECT *
FROM crime_scene_report
WHERE type = 'murder' AND date = (20180115) AND city = 'SQL City'

,date,type,description,city
0,20180115,murder,Security footage shows that there were 2 witnesses. The first witness lives at the last house o...,SQL City

##Encontrando a Annabel Miller y Morty Schapiro

Reunimos algunos datos de los dos principales testigos de la escena del crimen

In [ ]:
%%sql

SELECT *
FROM person
WHERE address_street_name IN ('Franklin Ave') AND name LIKE 'Annabel%'

      id            name  license_id  address_number address_street_name        ssn
0  16371  Annabel Miller      490173             103        Franklin Ave  318771143

In [ ]:
%%sql

SELECT *
FROM person
WHERE address_street_name IN ('Northwestern Dr')
order by address_number DESC

       id                  name  license_id  address_number address_street_name        ssn
0   14887        Morty Schapiro      118009            4919     Northwestern Dr  111564949
1   17729        Lasonya Wildey      439686            3824     Northwestern Dr  917817122
2   53890        Sophie Tiberio      957671            3755     Northwestern Dr  442830147
3   73368        Torie Thalmann      773862            3697     Northwestern Dr  341559436
4   96595         Coretta Cubie      303645            3631     Northwestern Dr  378403829
5   19420           Cody Schiel      890431            3524     Northwestern Dr  947110049
6   93509        Emmitt Aceuedo      916706            3491     Northwestern Dr  979073160
7   87456   Leonora Wolfsberger      215868            3483     Northwestern Dr  565203106
8   36378        Freddie Ellzey      267882            3449     Northwestern Dr  474117596
9   53076           Boris Bijou      664914            3327     Northwestern Dr  401191868
10  28360        Rashad Cascone      924517            3212     Northwestern Dr  838907424
11  23044          Val Portlock      924989            3143     Northwestern Dr  100593316
12  51114     Christena Saffell      814284            3055     Northwestern Dr  247657547
13  68690            Yer Modest      852404            3046     Northwestern Dr  419238039
14  44004           Alison Eska      327797            2951     Northwestern Dr  306417867
15  98593           Jonah Toner      578982            2947     Northwestern Dr  745853548
16  59307          Cyril Yongue      753524            2903     Northwestern Dr  866057839
17  34155      Allyson Lazenson      814209            2840     Northwestern Dr  991150469
18  90397     Dionna Kranwinkle      797260            2678     Northwestern Dr  278964807
19  54564         Sammie Sengun      217286            2590     Northwestern Dr  848854310
20  53699      Christian Pagano      628433            2585     Northwestern Dr  644772304
21  34352    Vincenza Burkhardt      436470            2512     Northwestern Dr  197913046
22  80921       Donovan Yackley      222395            2386     Northwestern Dr  515049359
23  96178           Galina Khuu      450248            2183     Northwestern Dr  398518185
24  81885         Kurtis Masuda      934201            2108     Northwestern Dr  201272595
25  88423           Teri Ehrich      510876            1879     Northwestern Dr  248637345
26  51552           Bonita Knie      764124            1726     Northwestern Dr  597137908
27  72076     Courtney Bordeaux      324614            1707     Northwestern Dr  347966356
28  81052     Calvin Czelusniak      471483            1516     Northwestern Dr  657531837
29  71924        Laurie Scronce      774116            1418     Northwestern Dr  254883636
30  23960  Kristopher Lagerberg      658777            1392     Northwestern Dr  492912529
31  70485     Andera Kostelecky      354822            1252     Northwestern Dr  787423012
32  22239         Dusty Sigafus      710517            1125     Northwestern Dr  724386723
33  18376              Josh Shi      653712            1091     Northwestern Dr  193899001
34  29608       Willetta Lurvey      800568            1028     Northwestern Dr  843751378
35  33415         Homer Simpson      108392             981     Northwestern Dr  871392019
36  55130        Shiloh Huntoon      472118             951     Northwestern Dr  826647644
37  44542        Ivory Mcgrevey      873842             897     Northwestern Dr  988557407
38  99826          Ivy Kazarian      994470             892     Northwestern Dr  208359813
39  25615         Olevia Morena      388477             812     Northwestern Dr  962831331
40  40760          Renata Faver      976650             745     Northwestern Dr  547572040
41  10010             Muoi Cary      385336             741     Northwestern Dr  828638512
42  39688            Abe Roeker      537445             689     Northwestern Dr  438969447
43  26758      Angelena Billman      942074             629     Northwestern Dr  341854756
44  75484          Del Tacderen      447887             607     Northwestern Dr  243821337
45  12711        Norman Apolito      667757             599     Northwestern Dr  778264744
46  85280             Donn Duin      569122             540     Northwestern Dr  613873810
47  40336       Fredia Billeter      251082             404     Northwestern Dr  108056488
48  15171          Weldon Penso      336999             311     Northwestern Dr  131379495
49  89906       Kinsey Erickson      510019             309     Northwestern Dr  635287661

##Entrevista a testigos Annabel y Morty

Revisamos las entrevistas correspondientes de los dos testigos. Esto fue lo que dijeron:

**Annabel** = *“Vi ocurrir el asesinato, y reconocí al asesino de mi gimnasio cuando estaba haciendo ejercicio la semana pasada el 9 de enero”*

**Morty** = *“Escuché un disparo y luego vi a un hombre salir corriendo. Tenía una bolsa de "Get Fit Now Gym". El número de membresía en la bolsa comenzaba con "48Z". Solo los miembros gold tienen esas bolsas. El hombre se subió a un coche con una placa que incluía "H42W".“*

In [ ]:
%%sql

SELECT *
FROM interview
WHERE person_id IN ('16371', '14887')

,person_id,transcript
0,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last we..."
1,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership nu..."

##Check in del 9 de enero

Averiguando sobre las personas que asistieron al "Get Fit Now Gym" ese 9 de enero que Annabel detalló y además según el id de membresía que vió el testigo Morty

In [ ]:
%%sql

SELECT *
FROM get_fit_now_check_in
WHERE check_in_date = 20180109 AND membership_id LIKE '48Z%'

  membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

##Placa de vehículo a donde subió el supuesto sospechoso

La placa del vehículo a la que se subió el supuesto asesino contenía los siguientes caracteres: ‘H42W…’

In [ ]:
%%sql

SELECT *
FROM drivers_license
WHERE plate_number LIKE 'H42W%'

       id  age  height eye_color hair_color  gender plate_number car_make car_model
0  183779   21      65      blue     blonde  female       H42W0X   Toyota     Prius

##Dueño del vehículo

La dueña del vehículo en el que se subió el asesino es ‘Maxine Whitely’

In [ ]:
%%sql

SELECT *
FROM person
WHERE license_id IN ('183779')

      id            name  license_id  address_number address_street_name        ssn
0  78193  Maxine Whitely      183779             110             Fisk Rd  137882671

##Miembros registrados en "Get Fit Now Gym"

Averiguamos quienes son los miembros del GYM que estuvieron ese 9 de enero según el id que vio el testigo Morty.

Estas dos personas, miembros gold del Gym hasta ahora son sospechosas del asesinato, ya que, los dos coinciden con las pistas que hemos reunido hasta ahora, desde la fecha, el status de miembro y el id de membresía.

In [ ]:
%%sql

SELECT *
FROM get_fit_now_member
WHERE membership_status = 'gold' AND id IN ('48Z7A', '48Z55')

      id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

##Entrevista sospechosos

Revisamos nuevamente las entrevistas, pero de estos dos sospechosos, solo se encontró una.

**Jeremy Bowers** = *“Fui contratado por una mujer con mucho dinero. No sé su nombre pero sé que mide alrededor de 5'5" (65") o 5'7" (67"). Tiene el cabello rojo y conduce un Tesla Model S. Sé que asistió al Concierto Sinfónico SQL 3 veces en diciembre de 2017.”*

In [ ]:
%%sql

SELECT *
FROM interview
WHERE person_id IN ('28819', '67318')

,person_id,transcript
0,67318,"I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5"" ..."

##Coincidencias con descripción de Jeremy

In [ ]:
%%sql

SELECT *
FROM drivers_license
WHERE hair_color = 'red' AND car_make = 'Tesla' AND gender = 'female'

       id  age  height eye_color hair_color  gender plate_number car_make car_model
0  202298   68      66     green        red  female       500123    Tesla   Model S
1  291182   65      66      blue        red  female       08CM64    Tesla   Model S
2  918773   48      65     black        red  female       917UU3    Tesla   Model S

In [ ]:
%%sql

SELECT *
FROM person
WHERE license_id IN ('202298', '291182', '918773')

      id              name  license_id  address_number address_street_name        ssn
0  78881          Red Korb      918773             107         Camerata Dr  961388910
1  99716  Miranda Priestly      202298            1883          Golden Ave  987756388
2  90700     Regina George      291182             332           Maple Ave  337169072

##Descubriendo a la mujer que describió Jeremy

Miranda Priestly es la mujer que contrató a Jeremy, coincide exactamente con su descripción.

In [ ]:
%%sql

SELECT *
FROM facebook_event_checkin
WHERE person_id IN ('99716', '90700')

   person_id  event_id            event_name      date
0      99716      1143  SQL Symphony Concert  20171206
1      99716      1143  SQL Symphony Concert  20171212
2      99716      1143  SQL Symphony Concert  20171229

In [ ]:
%%sql

SELECT *
FROM income
WHERE ssn = 987756388

         ssn  annual_income
0  987756388         310000

#CASO RESUELTO!!!

ASESINA ENCONTRADA!

In [ ]:
check_suspect("Miranda Priestly")

Congrats, you found the brains behind the murder!
Everyone in SQL City hails you as the greatest SQL detective of all time.
Time to break out the champagne!

True